export const FETCH_USER_COCKTAILS_START = "FETCH_USER_COCKTAILS_START";
export const FETCH_USER_COCKTAILS_SUCCESS = "FETCH_USER_COCKTAILS_SUCCESS";
export const FETCH_USER_COCKTAILS_FAIL = "FETCH_USER_COCKTAILS_FAIL";
